// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: "AIzaSyD2TMUD0sDjz7kmDzFW3G6eZe2Hm5V5V9E",
    authDomain: "epsel-smart-reader.firebaseapp.com",
    projectId: "epsel-smart-reader",
    storageBucket: "epsel-smart-reader.firebasestorage.app",
    messagingSenderId: "298974373091",
    appId: "1:298974373091:web:29de599fd4d210399591d6",
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: "AIzaSyCJO79Tc4RkyBNXB6Qt6xhwFxs6-sQ4Q_Q",
    appId: "1:298974373091:android:c578ddb55eae72559591d6",
    messagingSenderId: "298974373091",
    projectId: "epsel-smart-reader",
    storageBucket: "epsel-smart-reader.firebasestorage.app",
  );
}
